name: notepad
description: Note Pad App with Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animate_do: ^3.0.2
  flutter_svg: ^1.1.6
  auto_size_text: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^4.0.3
  flutter_switch: ^0.3.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
