name: notepad
description: Note Pad App with Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animate_do: ^3.0.2
  flutter_svg: ^2.0.10+1
  auto_size_text: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_switch: ^0.3.2
  table_calendar: ^3.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:

  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf


  assets:
    - assets/images/

